set(3DNOW                  OFF CACHE INTERNAL "")
set(ALSA                   OFF CACHE INTERNAL "")
set(ALSA_SHARED            OFF CACHE INTERNAL "")
set(ALTIVEC                ON  CACHE INTERNAL "")
set(ARMNEON                OFF CACHE INTERNAL "")
set(ARMSIMD                OFF CACHE INTERNAL "")
set(ARTS                   OFF CACHE INTERNAL "")
set(ARTS_SHARED            OFF CACHE INTERNAL "")
set(ASSEMBLY               ON  CACHE INTERNAL "")
set(ASSERTIONS             "disabled" CACHE INTERNAL "")
set(BACKGROUNDING_SIGNAL   OFF CACHE INTERNAL "")
set(CLOCK_GETTIME          OFF CACHE INTERNAL "")
set(DIRECTFB_SHARED        OFF CACHE INTERNAL "")
set(DIRECTX                OFF CACHE INTERNAL "")
set(DISKAUDIO              OFF CACHE INTERNAL "")
set(DUMMYAUDIO             OFF CACHE INTERNAL "")
set(ESD                    OFF CACHE INTERNAL "")
set(ESD_SHARED             OFF CACHE INTERNAL "")
set(FOREGROUNDING_SIGNAL   OFF CACHE INTERNAL "")
set(FUSIONSOUND            OFF CACHE INTERNAL "")
set(FUSIONSOUND_SHARED     OFF CACHE INTERNAL "")
set(GCC_ATOMICS            ON  CACHE INTERNAL "")
set(HIDAPI                 ON  CACHE INTERNAL "")
set(INPUT_TSLIB            OFF CACHE INTERNAL "")
set(JACK                   OFF CACHE INTERNAL "")
set(JACK_SHARED            OFF CACHE INTERNAL "")
set(JOYSTICK_VIRTUAL       ON  CACHE INTERNAL "")
set(KMSDRM_SHARED          OFF CACHE INTERNAL "")
set(LIBC                   ON  CACHE INTERNAL "")
set(LIBSAMPLERATE          OFF CACHE INTERNAL "")
set(LIBSAMPLERATE_SHARED   OFF CACHE INTERNAL "")
set(MMX                    ON  CACHE INTERNAL "")
set(NAS                    OFF CACHE INTERNAL "")
set(NAS_SHARED             OFF CACHE INTERNAL "")
set(OSS                    OFF CACHE INTERNAL "")
set(PTHREADS               OFF CACHE INTERNAL "")
set(PTHREADS_SEM           OFF CACHE INTERNAL "")
set(PULSEAUDIO             OFF CACHE INTERNAL "")
set(PULSEAUDIO_SHARED      OFF CACHE INTERNAL "")
set(RENDER_D3D             OFF CACHE INTERNAL "")
set(RENDER_METAL           OFF CACHE INTERNAL "")
set(RPATH                  OFF CACHE INTERNAL "")
set(SDL_ATOMIC             ON  CACHE INTERNAL "")
set(SDL_AUDIO              OFF CACHE INTERNAL "")
set(SDL_CMAKE_DEBUG_POSTFIX "d" CACHE INTERNAL "")
set(SDL_CPUINFO            ON  CACHE INTERNAL "")
set(SDL_DLOPEN             ON  CACHE INTERNAL "")
set(SDL_EVENTS             ON  CACHE INTERNAL "")
set(SDL_FILE               ON  CACHE INTERNAL "")
set(SDL_FILESYSTEM         OFF CACHE INTERNAL "")
set(SDL_HAPTIC             ON  CACHE INTERNAL "")
set(SDL_JOYSTICK           ON  CACHE INTERNAL "")
set(SDL_LOADSO             ON  CACHE INTERNAL "")
set(SDL_LOCALE             ON  CACHE INTERNAL "")
set(SDL_POWER              ON  CACHE INTERNAL "")
set(SDL_RENDER             OFF CACHE INTERNAL "")
set(SDL_SENSOR             ON  CACHE INTERNAL "")
set(SDL_SHARED             OFF CACHE INTERNAL "")
set(SDL_STATIC             ON  CACHE INTERNAL "")
set(SDL_STATIC_PIC         OFF CACHE INTERNAL "")
set(SDL_TEST               OFF CACHE INTERNAL "")
set(SDL_THREADS            ON  CACHE INTERNAL "")
set(SDL_TIMERS             ON  CACHE INTERNAL "")
set(SDL_VIDEO              ON  CACHE INTERNAL "")
set(SNDIO                  OFF CACHE INTERNAL "")
set(SNDIO_SHARED           OFF CACHE INTERNAL "")
set(SSE                    ON  CACHE INTERNAL "")
set(SSE2                   ON  CACHE INTERNAL "")
set(SSE3                   ON  CACHE INTERNAL "")
set(SSEMATH                ON  CACHE INTERNAL "")
set(VIDEO_COCOA            OFF CACHE INTERNAL "")
set(VIDEO_DIRECTFB         OFF CACHE INTERNAL "")
set(VIDEO_DUMMY            OFF CACHE INTERNAL "")
set(VIDEO_KMSDRM           OFF CACHE INTERNAL "")
set(VIDEO_METAL            OFF CACHE INTERNAL "")
set(VIDEO_OFFSCREEN        OFF CACHE INTERNAL "")
set(VIDEO_OPENGL           OFF CACHE INTERNAL "")
set(VIDEO_OPENGLES         OFF CACHE INTERNAL "")
set(VIDEO_RPI              OFF CACHE INTERNAL "")
set(VIDEO_VIVANTE          OFF CACHE INTERNAL "")
set(VIDEO_VULKAN           ON  CACHE INTERNAL "")
set(VIDEO_WAYLAND          OFF CACHE INTERNAL "")
set(VIDEO_WAYLAND_QT_TOUCH OFF CACHE INTERNAL "")
set(VIDEO_X11              OFF CACHE INTERNAL "")
set(VIDEO_X11_XCURSOR      OFF CACHE INTERNAL "")
set(VIDEO_X11_XINERAMA     OFF CACHE INTERNAL "")
set(VIDEO_X11_XINPUT       OFF CACHE INTERNAL "")
set(VIDEO_X11_XRANDR       OFF CACHE INTERNAL "")
set(VIDEO_X11_XSCRNSAVER   OFF CACHE INTERNAL "")
set(VIDEO_X11_XSHAPE       OFF CACHE INTERNAL "")
set(VIDEO_X11_XVM          OFF CACHE INTERNAL "")
set(WASAPI                 OFF CACHE INTERNAL "")
set(WAYLAND_SHARED         OFF CACHE INTERNAL "")
set(X11_SHARED             OFF CACHE INTERNAL "")

captal_download_submodule(apyre/external/sdl)
add_subdirectory(external/sdl EXCLUDE_FROM_ALL)

unset(3DNOW                   CACHE)
unset(ALSA                    CACHE)
unset(ALSA_SHARED             CACHE)
unset(ALTIVEC                 CACHE)
unset(ARMNEON                 CACHE)
unset(ARMSIMD                 CACHE)
unset(ARTS                    CACHE)
unset(ARTS_SHARED             CACHE)
unset(ASSEMBLY                CACHE)
unset(ASSERTIONS              CACHE)
unset(BACKGROUNDING_SIGNAL    CACHE)
unset(CLOCK_GETTIME           CACHE)
unset(DIRECTFB_SHARED         CACHE)
unset(DIRECTX                 CACHE)
unset(DISKAUDIO               CACHE)
unset(DUMMYAUDIO              CACHE)
unset(ESD                     CACHE)
unset(ESD_SHARED              CACHE)
unset(FOREGROUNDING_SIGNAL    CACHE)
unset(FUSIONSOUND             CACHE)
unset(FUSIONSOUND_SHARED      CACHE)
unset(GCC_ATOMICS             CACHE)
unset(HIDAPI                  CACHE)
unset(INPUT_TSLIB             CACHE)
unset(JACK                    CACHE)
unset(JACK_SHARED             CACHE)
unset(JOYSTICK_VIRTUAL        CACHE)
unset(KMSDRM_SHARED           CACHE)
unset(LIBC                    CACHE)
unset(LIBSAMPLERATE           CACHE)
unset(LIBSAMPLERATE_SHARED    CACHE)
unset(MMX                     CACHE)
unset(NAS                     CACHE)
unset(NAS_SHARED              CACHE)
unset(OSS                     CACHE)
unset(PTHREADS                CACHE)
unset(PTHREADS_SEM            CACHE)
unset(PULSEAUDIO              CACHE)
unset(PULSEAUDIO_SHARED       CACHE)
unset(RENDER_D3D              CACHE)
unset(RENDER_METAL            CACHE)
unset(RPATH                   CACHE)
unset(SDL_ATOMIC              CACHE)
unset(SDL_AUDIO               CACHE)
unset(SDL_CMAKE_DEBUG_POSTFIX CACHE)
unset(SDL_CPUINFO             CACHE)
unset(SDL_DLOPEN              CACHE)
unset(SDL_EVENTS              CACHE)
unset(SDL_FILE                CACHE)
unset(SDL_FILESYSTEM          CACHE)
unset(SDL_HAPTIC              CACHE)
unset(SDL_JOYSTICK            CACHE)
unset(SDL_LOADSO              CACHE)
unset(SDL_LOCALE              CACHE)
unset(SDL_POWER               CACHE)
unset(SDL_RENDER              CACHE)
unset(SDL_SENSOR              CACHE)
unset(SDL_SHARED              CACHE)
unset(SDL_STATIC              CACHE)
unset(SDL_STATIC_PIC          CACHE)
unset(SDL_TEST                CACHE)
unset(SDL_THREADS             CACHE)
unset(SDL_TIMERS              CACHE)
unset(SDL_VIDEO               CACHE)
unset(SNDIO                   CACHE)
unset(SNDIO_SHARED            CACHE)
unset(SSE                     CACHE)
unset(SSE2                    CACHE)
unset(SSE3                    CACHE)
unset(SSEMATH                 CACHE)
unset(VIDEO_COCOA             CACHE)
unset(VIDEO_DIRECTFB          CACHE)
unset(VIDEO_DUMMY             CACHE)
unset(VIDEO_KMSDRM            CACHE)
unset(VIDEO_METAL             CACHE)
unset(VIDEO_OFFSCREEN         CACHE)
unset(VIDEO_OPENGL            CACHE)
unset(VIDEO_OPENGLES          CACHE)
unset(VIDEO_RPI               CACHE)
unset(VIDEO_VIVANTE           CACHE)
unset(VIDEO_VULKAN            CACHE)
unset(VIDEO_WAYLAND           CACHE)
unset(VIDEO_WAYLAND_QT_TOUCH  CACHE)
unset(VIDEO_X11               CACHE)
unset(VIDEO_X11_XCURSOR       CACHE)
unset(VIDEO_X11_XINERAMA      CACHE)
unset(VIDEO_X11_XINPUT        CACHE)
unset(VIDEO_X11_XRANDR        CACHE)
unset(VIDEO_X11_XSCRNSAVER    CACHE)
unset(VIDEO_X11_XSHAPE        CACHE)
unset(VIDEO_X11_XVM           CACHE)
unset(WASAPI                  CACHE)
unset(WAYLAND_SHARED          CACHE)
unset(X11_SHARED              CACHE)
